AHADI_df <- tibble::tribble(
            ~County, ~CID, ~AHADI_focus,
          "BARINGO",   30,            0,
            "BOMET",   36,            1,
          "BUNGOMA",   39,            0,
            "BUSIA",   40,            0,
  "ELGEYO MARAKWET",   28,            0,
             "EMBU",   14,            0,
          "GARISSA",    7,            1,
         "HOMA BAY",   43,            0,
           "ISIOLO",   11,            1,
          "KAJIADO",   34,            0,
         "KAKAMEGA",   37,            1,
          "KERICHO",   35,            0,
           "KIAMBU",   22,            1,
           "KILIFI",    3,            0,
        "KIRINYAGA",   20,            0,
            "KISII",   45,            1,
           "KISUMU",   42,            0,
            "KITUI",   15,            0,
            "KWALE",    2,            0,
         "LAIKIPIA",   31,            0,
             "LAMU",    5,            1,
         "MACHAKOS",   16,            1,
          "MAKUENI",   17,            0,
          "MANDERA",    9,            1,
         "MARSABIT",   10,            1,
             "MERU",   12,            1,
           "MIGORI",   44,            0,
          "MOMBASA",    1,            1,
         "MURANG'A",   21,            1,
          "NAIROBI",   47,            1,
           "NAKURU",   32,            0,
            "NANDI",   29,            1,
            "NAROK",   33,            0,
          "NYAMIRA",   46,            1,
        "NYANDARUA",   18,            0,
            "NYERI",   19,            0,
          "SAMBURU",   25,            0,
            "SIAYA",   41,            1,
     "TAITA TAVETA",    6,            0,
       "TANA RIVER",    4,            0,
    "THARAKA NITHI",   13,            1,
      "TRANS NZOIA",   26,            1,
          "TURKANA",   23,            1,
      "UASIN GISHU",   27,            0,
           "VIHIGA",   38,            1,
            "WAJIR",    8,            1,
       "WEST POKOT",   24,            0
  )
