## Purpose: Process household survey modules for use in regression models on shocks
# Apply survey weights using the survey, srvyr, and svywrangler packages
# https://github.com/gergness/srvyr
# Author: Tim Essam, Ph.D | USAID GeoCenter
# Date: 2019/04/29
# Audience: Kenya Mission



# Preliminaries -----------------------------------------------------------


# Check what is loaded and inclued in existing directories and files generated by 00_Setup and 02_KIHBS_shocks
dir(kihbspath)
map(list(hh_base, hh_info), ~vtable(.))
source(file.path(rpath, "twoToZero.R"))

# prep functions

# Household Info file contains Housing, water and sanitation, energy, transfers, other income, food insecurity, ICT



# Dwelling information ----------------------------------------------------

hh_chars <- 
  hh_info %>% 
  select(county, strat, resid, eatype, qrt, cycle, clid, hhid, hhsize, weight,
         ctry_adq, iday,
        
        # Housing 
        home_type = i01,
         home_own = i02,
         home_age = i06,
         home_value = i07,
         room_size = i12_1,
         wall_type = i13,
         roof_type = i14,
         floor_type = i15,
         cook_type = i16,
         energy_light = j17,
        
        # Transfers
        hh_support = o01,
        transfers_amt = o02_h,
        
        # Food security --> Section QA pg 24
        food_worry = qa1,
        food_pref_money = qa2,
        food_fewer_money = qa3,
        food_miss_meal = qa4,
        food_eat_less = qa5,
        food_runout = qa6,
        food_hungry = qa7,
        food_without_day = qa8,
        food_relief = qa9,
        
        # ICT --> Section S pg 29
        computer = s01,
        tv = s02,
        internet = s09,
        internet_phone = s10_1
        ) %>%
  
  mutate(
  # Create dummies for variants of infrastructure for wealth index to be used later
    home_bungalow = ifelse(home_type %in% c(1, 2, 3), 1, 0),
    home_swahili = ifelse(home_type %in% c(4), 1, 0),
    home_shanty = ifelse(home_type %in% c(5), 1, 0),
    home_manyatta = ifelse(home_type %in% c(6, 7), 1, 0),
    own_home = ifelse(home_own == 1, 1, 0),
    
    nat_walls = ifelse(wall_type %in% c(1, 2, 3, 4), 1, 0),
    rud_walls = ifelse(wall_type %in% c(5, 6, 7, 8, 9, 10, 11), 1, 0),
    fin_walls = ifelse(wall_type %in% c(12, 13, 14, 15, 16, 17), 1, 0),
    
    nat_roof = ifelse(roof_type %in% c(1, 2), 1, 0),
    rud_roof = ifelse(roof_type %in% c(3, 4), 1, 0),
    fin_roof = ifelse(roof_type %in% c(5, 6, 7), 1, 0),
    
    nat_floor = ifelse(floor_type %in% c(1, 2), 1, 0),
    rud_floor = ifelse(floor_type %in% c(3, 4), 1, 0),
    fin_floor = ifelse(floor_type %in% c(5, 6, 7, 8, 9), 1, 0),
    
    fire_stove = ifelse(cook_type %in% c(1, 2), 1, 0),
    jiko_stove = ifelse(cook_type %in% c(3, 4), 1, 0),
    fuel_stove = ifelse(cook_type %in% c(5, 6, 7, 8), 1, 0),
    
    elect_conn = ifelse(energy_light == 1, 1, 0),
    
    transfers = ifelse(hh_support == 1, 1, 0)
    ) %>% 
  
  # Convert questions where 2 = no to 0s -- applying to food security questions
  mutate_at(vars(contains("food_")), twoToZero) %>% 
  mutate_at(vars(c("computer", "internet", "tv")), twoToZero)

# Test that all binary variables are really binary
hh_chars %>% select_if(~is.numeric(.) & max(., na.rm=TRUE) == 1) %>% 
  names()



# Check the sample design  
housing_svy <- hh_chars %>% 
  as_survey_design(id = clid, strata = strat, weights = weight)

housing_svy %>% 
  select(contains("food_")) %>% 
  summarise_all(survey_mean, na.rm = TRUE) %>% 
  select(-contains("_se")) %>% 
  gather(var, value)
                             

         
         
         
                       
