# List of County flags that have been developed over course of project

county_list <- tibble::tribble(
          ~Counties, ~CID,                      ~Category, ~AHADI_flag,
          "Mombasa",    1,              "Non-ASAL County",           1,
            "Kwale",    2, "Semi - Arid - 30-84% Aridity",           0,
           "Kilifi",    3, "Semi - Arid - 30-84% Aridity",           0,
       "Tana River",    4,       "Arid - 85-100% Aridity",           0,
             "Lamu",    5, "Semi - Arid - 10-29% Aridity",           1,
     "Taita Taveta",    6, "Semi - Arid - 30-84% Aridity",           0,
          "Garissa",    7,       "Arid - 85-100% Aridity",           1,
            "Wajir",    8,       "Arid - 85-100% Aridity",           1,
          "Mandera",    9,       "Arid - 85-100% Aridity",           1,
         "Marsabit",   10,       "Arid - 85-100% Aridity",           1,
           "Isiolo",   11,       "Arid - 85-100% Aridity",           1,
             "Meru",   12, "Semi - Arid - 30-84% Aridity",           1,
    "Tharaka Nithi",   13, "Semi - Arid - 30-84% Aridity",           1,
             "Embu",   14, "Semi - Arid - 30-84% Aridity",           0,
            "Kitui",   15, "Semi - Arid - 30-84% Aridity",           0,
         "Machakos",   16, "Semi - Arid - 30-84% Aridity",           1,
          "Makueni",   17, "Semi - Arid - 30-84% Aridity",           0,
        "Nyandarua",   18,              "Non-ASAL County",           0,
            "Nyeri",   19, "Semi - Arid - 10-29% Aridity",           0,
        "Kirinyaga",   20,              "Non-ASAL County",           0,
         "Murang'a",   21,              "Non-ASAL County",           1,
           "Kiambu",   22, "Semi - Arid - 10-29% Aridity",           1,
          "Turkana",   23,       "Arid - 85-100% Aridity",           1,
       "West Pokot",   24, "Semi - Arid - 30-84% Aridity",           0,
          "Samburu",   25,       "Arid - 85-100% Aridity",           0,
      "Trans Nzoia",   26,              "Non-ASAL County",           1,
      "Uasin Gishu",   27,              "Non-ASAL County",           0,
  "Elgeyo Marakwet",   28, "Semi - Arid - 10-29% Aridity",           0,
            "Nandi",   29,              "Non-ASAL County",           1,
          "Baringo",   30, "Semi - Arid - 30-84% Aridity",           0,
         "Laikipia",   31, "Semi - Arid - 30-84% Aridity",           0,
           "Nakuru",   32, "Semi - Arid - 10-29% Aridity",           0,
            "Narok",   33, "Semi - Arid - 10-29% Aridity",           0,
          "Kajiado",   34, "Semi - Arid - 30-84% Aridity",           0,
          "Kericho",   35,              "Non-ASAL County",           0,
            "Bomet",   36,              "Non-ASAL County",           1,
         "Kakamega",   37,              "Non-ASAL County",           1,
           "Vihiga",   38,              "Non-ASAL County",           1,
          "Bungoma",   39,              "Non-ASAL County",           0,
            "Busia",   40,              "Non-ASAL County",           0,
            "Siaya",   41,              "Non-ASAL County",           1,
           "Kisumu",   42,              "Non-ASAL County",           0,
         "Homa Bay",   43, "Semi - Arid - 10-29% Aridity",           0,
           "Migori",   44, "Semi - Arid - 10-29% Aridity",           0,
            "Kisii",   45,              "Non-ASAL County",           1,
          "Nyamira",   46,              "Non-ASAL County",           1,
          "Nairobi",   47,              "Non-ASAL County",           1
  )
